### PR TITLE
Adds reproducibility files for running AMRFinderPlus on ATB

### LINKED ISSUE #29: Run AMRFinderPlus

### PR DESCRIPTION
**Pull request by Danderson123**
Includes a snakemake workflow used to run AMRFinderPlus in batches as well as a README specifying software and database versions and inputs.

closes #29.

### CODE REVIEW

**Comment by Danderson123** [comment]
@martinghunt let me know if there is anything you want me to add to this.

**Comment by martinghunt** [comment]
Can you add any relevant files for reproducibility to OSF if possible? And then link to them in the readme here?

I only have on my on branch, not added here yet, but eg for the assembly pipeline I added all the files I could to OSF (except slyph db because at 11GB it's too big for OSF). Draft readme is here: https://github.com/martinghunt/AllTheBacteria/tree/assembly_repro_post_0.2/reproducibility/All-samples/assembly
See the list of wget commands for example.

**Comment by Danderson123** [comment]
Status file is up on OSF too, happy to merge?

**Comment by martinghunt** [comment]
Yes!

**Pull request merged**
